version: '3'
services:
  demo-app:
    build:
      dockerfile: "./Dockerfile_v2"
    volumes:
      - .dockervenv:/src/.venv
      - .:/src
    ports:
      - 8000:8000  # ホストマシンのポート8000を、docker内のポート8000に接続する